### ISSUE TITLE
修改单位

### ISSUE THREAD

**Issue by baiyucraft** [sxguojf/three-tile#11]
你好，我现在在使用three-tile中遇到个问题，原代码中投影的坐标是1单位对应1km，我想实现1单位对应1m，该怎么修改呢

**Comment by baiyucraft** [comment]
看了下之前的issue，使用scale的方式不太能接受。能不能请大佬说下要大概思路或者要改哪几个文件，方便去定位修改，谢谢啦

**Comment by sxguojf** [comment]
为什么不接受scale？要将坐标单位改成米，两种方法：
1. 把地图模型放大1000倍，创建地图后加上：map.scale.setScalar(1000);
2. 把你要加的以米为单位的模型等缩小1000倍：model.scale.setScale(0.001);

不用纠结scale，3D世界本来是没有具体单位的。three-tile原始地图模型是1个单位，为了符合人类直觉，我把它用setScale直接拉伸到地球KM为单位的周长。用KM完全是因为我嫌0太多，偷了个懒....

你如果是自己创建的threejs场景，那只需要简单scale下地图或模型即可，其它的都不用改。

你如果要用内置的GLViewer类，因为这个里面的摄像机、灯光、控制器、高度、雾范围等都用的是KM为单位的值，将地图模型Scale后，这些值也要改为M为单位。Example项目里， thttps://sxguojf.github.io/three-tile-example/ 的2.12有加载3D-Tiles例子，它是将单位改为M的，可以参考它。

**Comment by baiyucraft** [comment]
好的，我再试试，谢谢
