### ISSUE TITLE
如何解决

### ISSUE THREAD

**Issue by red-fire-code** [sxguojf/three-tile#6]
![QQ20240725-114619](https://github.com/user-attachments/assets/cd13fd8b-4d53-4adc-b48a-536c98ea4931)
你好，我们这边偏要我们前端解决瓦片请求不到会出现黑边的问题，请问前端有办法解决吗？

**Comment by sxguojf** [comment]
1、默认情况，瓦片请求失败会显示为透明的，你贴图中显示为黑色，应该地图加了黑色背景。
2、请求不到瓦片，你想显示成什么样呢？
3、如果已经确定一些瓦片不存在，可以继承TileSource写一个类，重载其getUrl函数，当请求瓦片的xyz坐标不存在时，返回一张图片url代替。
4、请求不到瓦片从服务器端解决简单高效，费这劲没有意义。

**Comment by red-fire-code** [comment]
郭佬，请问一下，这个组件有一个很严重的问题，就是由于是经纬度转世界坐标，然后值很大，导致着色器在传递的时候会出现严重的精度丢失。尤其是在移动的时候极其严重。有好的解决办法吗？网上也找到一些，还是想听听您的建议。

**Comment by sxguojf** [comment]
这个问题是因为着色器的float坐标只有7位有效数字，使用投影坐标传入着色器大概只能到精确到米级。网上有一些解决方案：
1、cesium：坐标使用高低位部分两个数表示，着色器中将这两个数合成为一个数提高精度
2、mapbox：将投影坐标转为相对于瓦片的坐标，减少坐标值以增加有效数字位
但这两种方法需要重写threejs内置着色器，并对模型顶点坐标进行转换。three-tile主要是利用threejs现有生态，如果所有模型修改重写，那使用它的意义就不大了。

既然精度损失的主要原因是模型的坐标数值过大，传入着色器后有效位数不够造成的，那模型就不要直接用世界坐标，试试如下方式解决：
1、给TileMap中增加一个group，将这个group的中心调整到你的地图中心，如北京市，后面你在地图上添加的模型均加入该group。
2、将需要添加的模型坐标从世界坐标转换为相对于group的坐标，这个坐标值会比较小，能够满足精度需求。
3、鼠标点击时，也同样将点击的世界坐标转换为相对于group的坐标，然后再将模型加入group。

总之，three-tile仅提供一个地图三维模型，其上添加什么还是按threejs的方法，与地图无关。你甚至可以用threejs完成基本功能开发后，再添加three-tile，用TileMap替换原有的Plane地面模型，再把模型移动到合适的位置。

**Comment by red-fire-code** [comment]
> 那模型就不要直接用世界坐标，

好的，谢谢，第一个试了，有些效果，你说的第三个方法，好像可行性也不错，我去尝试下
