### ISSUE TITLE
请问有对cesium的高程文件或者天地图的高程文件有过了解吗？

### ISSUE THREAD

**Issue by FengFengmomo** [sxguojf/three-tile#9]
最近在研究高程数据，发现mapbox的那种高程表现方式已经过时了，现在都是TIN STK格式的数据。
然后发现是cesium研发的，同时天地图的高程数据也支持该该格式，但是目前对js的文件解析不太了解。
看了一篇文章说的挺对，也是位大佬写的，https://www.cnblogs.com/fuckgiser/p/5883227.html。
这篇文章介绍了，但是还是不太明白如何解析文件。

**Comment by sxguojf** [comment]
cesium地形瓦片支持Heightmap和Quantized-Mesh两种格式，Heightmap格式类似Mapbox的地形瓦片以栅格形式保存地图数据，Quantized-Mesh直接保存顶点，数据量更小，速度也更快。天地图的地形是Quantized-Mesh格式。
Quantized-Mesh自己解析比较复杂，但有一些开源库支持，如 https://github.com/heremaps/quantized-mesh-viewer

three-tile早期曾支持cesium的Quantized-Mesh和arcgis的lerc格式，但很少有人有这个需求，现已废弃。

目前three-tile支使用的mapbox的terrain-rgb格式，虽然有些缺点，但它以图片方式保存高程，有大量开源库支持，用户很方便地用tif高程制作自己的地形瓦片。

**Comment by hme-support** [comment]
Hi @sxguojf , I have a dxf file with elevation data. Is there anyway I can use the data from the dxf file to render 3D Tiles? Thanks!

**Comment by sxguojf** [comment]
three-tile does not support DXF file directly, but you can convert DXF files to formats like GLB,( https://www.3dpea.com/en/convert/DXF-to-GLB ) and using Three.js to render the model and place it at the specified position on the map.

**Comment by hme-support** [comment]
Ok, but I want to use the elevation data from the dxf and set it to the tiles. Is there any way I can do that? If it is not possible how can I load the custom elevation data to tiles.

**Comment by sxguojf** [comment]
three-tile only supports  [Terrain-RGB](https://docs.mapbox.com/data/tilesets/reference/mapbox-terrain-rgb-v1/) map tiles。 convert the DXF files to raster images, and the use of GDAL to clip those raster images into Terrain-RGB map tiles。

To load the custom elevation data，see (https://sxguojf.github.io/three-tile-example/  ) step4.6，but to parse DXF and create DEM mesh is too difficult....

**Comment by Krishnadas7** [comment]
Hi @sxguojf im trying to add an .tif the path is correct but it not showing in browser and tried to add png file it successfully showing why the tif format is not opening?

**Comment by sxguojf** [comment]
three-tile does not support .tif format tile directly.

**Comment by Krishnadas7** [comment]
@sxguojf could you please explain about 
How can we show .tif files and display elevation data in three-tile? What data files can be used for visualization?

**Comment by sxguojf** [comment]
three-tile elevation data support Mapbox Terrain-RGB and ArcGIS lerc  format  terrain tiles，convert the .tif files to .jpg or .png or .webp... tiles use GDAL.

**Comment by hme-support** [comment]
Hi Guojf,

At the moment we have .dxf, .tif and a .geojson files which the elevation data for a specific region. We really liked the way three-tile loads the details at various zoom levels. We want to use that as part of our project. Can you please help us with information on how to create a terrain RGB with the data we have?  A guidance will be really helpful.

From: guojf ***@***.***>
Date: Wednesday, 22 January 2025 at 11:57 am
To: sxguojf/three-tile ***@***.***>
Cc: Support ***@***.***>, Comment ***@***.***>
Subject: Re: [sxguojf/three-tile] 请问有对cesium的高程文件或者天地图的高程文件有过了解吗？ (Issue #9)

three-tile elevation data support Mapbox Terrain-RGB and ArcGIS lerc format terrain tiles，convert the .tif files to .jpg or .png or .webp... tiles use GDAL.

**Comment by Krishnadas7** [comment]
Hi @sxguojf ,
I've been working on adapting the code from your Rio RGBify GitHub repository to JavaScript.

I've successfully generated output tiles from a .tif image, but all the tiles are appearing black.

I'm seeking guidance on the potential causes of this issue. Could you please point me towards areas I should investigate to troubleshoot this problem?

**Comment by sxguojf** [comment]
try: rio rgbify -b -10000 -i 0.1 xxxx.tif xxxx_rgb.tif

**Comment by Krishnadas7** [comment]
Hy @sxguojf 
 Could you please provide additional information or a step-by-step guide? I am still facing issues with this command.
rio rgbify -b -10000 -i 0.1 xxxx.tif xxxx_rgb.tif

**Comment by sxguojf** [comment]
@Krishnadas7 

I Can't explain clearly in English, explain in Chinese：

[rio-rgbify](https://github.com/mapbox/rio-rgbify) 是 MapBox 的将 tif 高程数据换为terrain-rgb编码图像的程序，它使用图像RGB三个分量保存地形海拔高度。这里的tif，实际上是geotiff，并非一般图像，包含了地理信息，如经纬度范围、投影，通道等。

网上有很多转换教程：
https://beginor.github.io/2021/01/11/publish-dem-data-with-mapbox-terrain-rgb.html
https://blog.csdn.net/wg22222222/article/details/135907737
https://www.maptiler.com/news/2019/03/rgb-encoded-elevation-data-in-maptiler-cloud/
https://github.com/syncpoint/terrain-rgb/tree/master?tab=readme-ov-file
https://medium.com/@frederic.rodrigo/optimization-of-rgb-dem-tiles-for-dynamic-hill-shading-with-mapbox-gl-or-maplibre-gl-55bef8eb3d86

**Comment by Krishnadas7** [comment]
I have converted a .tif file into Terrain RGB and created tiles in a folder using GDAL. After that, I hosted the tiles on a server and added the tile URL into the Mapbox configuration. The setup is working fine, and I can access the tiles from the live server on Mapbox without any issues.

However, I am now planning to use the tiles with a three tile setup, and I’m facing an issue with rendering. I suspect there might be a mistake in the final steps after creating the tiles, hosting the server, or using the URL in the configuration.

Here is the code I am currently using:

export const mapBoxImgSource = new tt.plugin.MapBoxSource({
    token: mapBoxKey, // The API key to access Mapbox services.
    dataType: "image", // Specifies that the data is an image (e.g., satellite imagery).
    style: "mapbox.satellite", // Defines the map style (satellite view).
    url: "http://127.0.0.1:5500/ftiles/{z}/{x}/{y}.png" // Tile source URL.
});

Questions:
Am I generating the tile URL correctly for use in the three.js setup?
Is there a mistake in hosting the tiles or configuring the server?
How can I correctly display these tiles in Mapbox or three.js?

**Comment by Krishnadas7** [comment]
Hy   @sxguojf   
我已使用 GDAL 将 .tif 文件转换为 Terrain RGB，并在一个文件夹中生成了瓦片。之后，我在服务器上托管了这些瓦片，并将瓦片 URL 添加到了 Mapbox 配置中。目前，该设置运行良好，我可以在 Mapbox 上通过实时服务器访问这些瓦片，没有任何问题。

然而，现在我计划在 three tile 设置中使用这些瓦片，但在渲染时遇到了一些问题。我怀疑可能是在创建瓦片、托管服务器或使用 URL 进行配置的最后步骤中出现了错误。

以下是我目前使用的代码：

export const mapBoxImgSource = new tt.plugin.MapBoxSource({
    token: mapBoxKey, // 用于访问 Mapbox 服务的 API 密钥。
    dataType: "image", // 指定数据类型为图像（例如，卫星图像）。
    style: "mapbox.satellite", // 定义地图样式（卫星视图）。
    url: "http://127.0.0.1:5500/ftiles/{z}/{x}/{y}.png" // 瓦片来源 URL。
});
问题：
我生成的瓦片 URL 是否适用于 three.js 设置？
瓦片托管或服务器配置是否有错误？
我如何在 Mapbox 或 three.js 中正确显示这些瓦片？

**Comment by sxguojf** [comment]
请参考demo中的代码，这是一段加载小区域瓦片的：

`setBoundsTile: () => {
        //bounds of tiles , lon,lat
	const bounds: [number, number, number, number] = [
		108.60157012939453, 30.64670562744141, 108.65313291549683, 30.69008231163025,
	];
	const urlPrefix = "http://127.0.0.1:5500/testSource";
	const imgSource = tt.TileSource.create({
                dataType: "image"
		url: urlPrefix + "/img/{z}/{x}/{y}.png",
		bounds,
		minLevel: 0,
		maxLevel: 15,
	});

	const demSource = tt.TileSource.create({
		dataType: "terrain-rgb",
		url: urlPrefix + "/dem/{z}/{x}/{y}.png",
		bounds,
		minLevel: 5,
		maxLevel: 15,
	});

	map.imgSource = [ms.arcGisSource, imgSource, ms.testSource];
	map.imgSource = imgSource;
	map.demSource = demSource;

	// Move the camera to the bounds
	viewer.controls.target.copy(map.geo2world(new Vector3(108.627984, 30.66284, 0.0)));
	viewer.camera.position.copy(map.geo2world(new Vector3(108.627139, 30.64138, 3.309163)));
	map.reload();
},`

如果你的瓦片服务不用限制范围，那更简单：
`setYourSource: () => {
	map.imgSource = TileSource.create({
		url: "[http://127.0.0.1:5500/ftiles/{z}/{x}/{y}.png]”;
	});
	map.reload();
},`

**Comment by Krishnadas7** [comment]
Hy @sxguojf 
could you please provide any another docs?

**Comment by sxguojf** [comment]
@Krishnadas7 

https://blog.csdn.net/HZGJF/article/details/140396832

**Comment by Krishnadas7** [comment]
Hy @sxguojf  ,
Now im able to show the tiles but "I am currently facing an issue where, when zoomed in, the URL is calling localhost:8000/2/1/1.png, but this folder does not exist in my tiles folder. Could you please help me adjust the configuration so that it correctly points to the existing tiles?"

**Comment by sxguojf** [comment]
```typscript
// 创建地图对象
const map = new tt.TileMap({
	// 影像数据源
	imgSource: imgSource,
	// 高程数据源
	demSource: demSource,
	// 地图投影中央经线经度
	lon0: 90,
	// 最小缩放级别
	minLevel: 2,
	// 最大缩放级别
	maxLevel: 20,
});

````
创建地图时，设置 minLevel参数为你的最小瓦片层级（文件夹），2不存在就设置为3。maxLevel设置为你的瓦片最大层级

**Comment by Krishnadas7** [comment]
Hy @sxguojf   
I tried using an image, and it opens successfully. However, I need to work with a smaller image. When creating tiles with zoom levels like 2–15 or 5–10, the image displays but appears too small to view properly. Additionally, the output doesn't render as expected, with parts of the image seeming misaligned or fragmented. I would appreciate guidance on troubleshooting this issue.

**Comment by sxguojf** [comment]
@Krishnadas7 
没明白你的意思，贴张有问题的图看看

**Comment by Krishnadas7** [comment]
![Image](https://github.com/user-attachments/assets/cff065f8-a41d-497d-95e5-d60983528140)

this is the final output and 

![Image](https://github.com/user-attachments/assets/a777d5d5-fb52-4ed9-855e-a3fbe9c5b5d2)
this is the image im trying to showing in three-tile

**Comment by sxguojf** [comment]
你要叠加的图片比较小，裁成瓦片的意义不大，可以直接将整张图片加上去。

地图上可以叠加单张小图片，是刚发布的three-tile V0.8.1新增功能。升级一下three-tile，添加数据源：

```typescript
// HME source test
export const hmeSource = new tt.TileSource({
	dataType: "single-image",
	url: "./images/240817_Site.jpg",
	bounds: [120.42726278178006, -29.136928155878874, 120.47713619176932, -29.166196150519955],
});
```
另外，TileMap.imgSorce可以是一个数组，能添加多个数据源叠加。

![Image](https://github.com/user-attachments/assets/37a7a418-8be9-40f2-8a5f-87b8427ab0b5)

**Comment by Krishnadas7** [comment]
const MapView = () => {
  const geoFences = useRef<any>([]);

  useEffect(() => {
    // Create the map
    const map:any = util.createMap(ms.mapBoxImgSource, ms.mapBoxDemSource);
    const centerGeo = new Vector3(82.4, 30.0, 0.0); // Geographical coordinates
    const cameraGeo = new Vector3(2228.02, 23.91, -3475.44); // Camera position
    
    // Create viewer
    const viewer: any = util.createViewer("#map-view", map, centerGeo, cameraGeo);
    console.log(viewer);

    viewer.controls.saveState();
    console.log(viewer.renderer.info);

    document.querySelector("#for-new-map")?.addEventListener("click", () => {
      // 用Source的create方法创建数据源
      
      map.imgSource = tt.TileSource.create({
        dataType: "single-image",
        bounds: [120.42726278178006, -29.136928155878874, 120.47713619176932, -29.166196150519955],
        url: "http://localhost:4000/tiles3/{z}/{x}/{y}.png", // Fix the quote here,
      });
      
    
      map.reload();
    });
  }, []);

  return (
    <React.Fragment>
      <button id='for-new-map'>XXXXXXXXXXXXXX</button>
      <div style={{ height: '95vh', width: '90%', background: 'black' }} id='map-view'></div>
    </React.Fragment>
  );
};

export default MapView;
document.querySelector("#for-new-map")?.addEventListener("click", () => {
      // 用Source的create方法创建数据源
      
      map.imgSource = tt.TileSource.create({
        dataType: "single-image",
        bounds: [120.42726278178006, -29.136928155878874, 120.47713619176932, -29.166196150519955],
        url: "http://localhost:4000/tiles3/{z}/{x}/{y}.png", // Fix the quote here,
      });
      
    
      map.reload();
    });
i need to show here now it is showing single-image data type is not support

**Comment by Krishnadas7** [comment]
I have an image in .tif format.
I converted it into a Terrain RGB file.
Using GDAL, I created the tiles for the image.
I then hosted the resulting folder on an Express server.
After that, I added the URL of the tiles to a Three.js tile source.

The issue I’m facing is that the image does not display correctly. It appears too small, and when I zoom in, it shows the image in two separate parts.

I followed the steps outlined in this document:
https://blog.csdn.net/HZGJF/article/details/140396832

Everything seems to work as expected up to that point, but I cannot get the image to display properly. Could you help me troubleshoot this issue?

**Comment by sxguojf** [comment]
@Krishnadas7 

1、升级three-tile到最新版本：V0.8.1，它支持"single-image"
2、如果你已经用做好了瓦片服务，那数据源的url改为：url: "http://localhost:4000/tiles3/{z}/{x}/{y}.png"
3、地图太小，是因为摄像机离地图太远，鼠标滚轮放大地图，或修改摄像机坐标：https://blog.csdn.net/HZGJF/article/details/140398295


这里是three-tile的示例，可以参考：https://github.com/sxguojf/three-tile-example

**Comment by sxguojf** [comment]
@Krishnadas7 

1、升级three-tile到最新版本：V0.8.1，它支持"single-image"
2、如果你已经用做好了瓦片服务，那数据源的url改为：url: "http://localhost:4000/tiles3/{z}/{x}/{y}.png"，数据类型改为：dataType:"image"
3、地图太小，是因为摄像机离地图太远，鼠标滚轮放大地图，或修改摄像机坐标：https://blog.csdn.net/HZGJF/article/details/140398295


这里是three-tile的示例，可以参考：
https://sxguojf.github.io/three-tile-example/
https://github.com/sxguojf/three-tile-example

**Comment by Krishnadas7** [comment]
> 你要叠加的图片比较小，裁成瓦片的意义不大，可以直接将整张图片加上去。
> 
> 地图上可以叠加单张小图片，是刚发布的three-tile V0.8.1新增功能。升级一下three-tile，添加数据源：
> 
> // HME source test
> export const hmeSource = new tt.TileSource({
> 	dataType: "single-image",
> 	url: "./images/240817_Site.jpg",
> 	bounds: [120.42726278178006, -29.136928155878874, 120.47713619176932, -29.166196150519955],
> });
> 另外，TileMap.imgSorce可以是一个数组，能添加多个数据源叠加。
> 
> ![Image](https://github.com/user-attachments/assets/37a7a418-8be9-40f2-8a5f-87b8427ab0b5)

Could you please delete this image from this public repository?

**Comment by sxguojf** [comment]
OK

**Comment by Krishnadas7** [comment]
Hy  @sxguojf 

If the map view is displayed correctly, will it automatically render in 3D, or do any additional steps need to be taken? Additionally, I have a .dxf file that I would like to display on this map. Could you please provide clarification on both of these points and guide me on how to proceed?

**Comment by Krishnadas7** [comment]
Hy  @sxguojf   

The three-tile view is truly an optimized solution for rendering maps—thank you for guiding me through it. I was wondering if you could share any repositories or additional documentation that showcase the usage of tiles in three-tile, especially for displaying the tiles on a map. Previously, you shared documentation for tile creation, which was very helpful, but I’d like to explore more about rendering and showcasing these tiles effectively.

If you could provide any further resources or examples, it would greatly assist me in moving to the next step.

Thank you!

**Comment by sxguojf** [comment]
@Krishnadas7 

1、文档主要就是首页的内容; 
2、基本用法在我的blog：https://blog.csdn.net/hzgjf；
3、api在项目的docs目录；
4、还有几十个使用使用示例: https://github.com/sxguojf/three-tile-example; 

我觉得已经足够了，但大部分是中文，特别是代码注释，老外看不太懂。

MapTile通过imgSource属性显示影像，通过demSource属性生成地形，如果没给demSource赋值，那显示的平面地图。一般demSoruce使用MapBox提供的terrain-RGB格式瓦片地图服务即可显示3D地形。

如果你要使用的自己的影像和地形瓦片，那需要了解瓦片地图的基本原理，可以看看leaflet、mapbox、cesium等。

dxf格式我不是太了解，如果你的dxf是三维对象，那可以试试把它作为三维模型添加到地图上；如果是三维地形数据，那比较麻烦，需要把它绘制成图片，再转换为terrain-RGB格式瓦片。
